INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("General Manager, CN & ISP",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, B2B",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Executive Manager,HRA",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, International Services",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Regional  Manager",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, ERP, CC and IT Support",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, Payment",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, Procurement&Inventory",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, SPPD",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Senior Driver",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, ISP Access",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer(Core Network)",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, IN",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, Access Network",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Supervisor, Civil",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Accountant",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Customer Care Executive",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician (Access network)",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Senior Customer Care Executive",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Contact Center Executive",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Supervisor, Access Network",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Supervisor, Core Network",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Superviser",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician (Core Network)",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Supervisor, Projects",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical  Superviser",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Accountant, Payment",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Driver",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Store Assistant",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician, Access Network",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, Core Network",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Marketing Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Officiating General Manager,Commercial",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, Power & Utilities",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Accounts Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician, Civil",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician, ISP Access",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician, Projects",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, Administration",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, B2C",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, Civil",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Senior Personal Assistant",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, Power & Utility",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, CBS",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, B2C",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Inventory Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Roaming Coordinator",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("General Manager, Finance",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Strategy Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Optimization  Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Officiating Manager, Human Resource",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician, Power",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Core Network Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Oficer (VAS)",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Regional Manager",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Bill Collector",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("CBS Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, VAS",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician (MIS)",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Accounts Officer, Payment",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Project  Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Manager, Access Network",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Optimization Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Project Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer,B2B",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician, Samsung",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Revenue Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, ISP Access",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Contact Center Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Webmaster",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("System  Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Human Resource  Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Procurement  Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("General Manager, SPPD",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("General Manager, Access",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("General Manager, MIS",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Graphic Designer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("PR and Administrative Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, Samsung",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Engineer VAS",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Audit Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Assistant Revenue Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Human  Resource Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Administrative Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Access Network Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("ERP Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("General Manager, Commercial",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Application Developer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer(Access Network)",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Human Resource Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technical Officer, Power & Utility",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Revenue Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Inventory Officer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("MFS Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("TDA Engineer",1,128,NOW());
INSERT INTO mas_designation (Name,Status,CreatedBy,created_at) VALUES ("Technician, Core Network",1,128,NOW());

UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'Application & Software Project') where T1.EmpId = 37;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2C Projects') where T1.EmpId = 106;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2B Projects') where T1.EmpId = 173;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2C Projects') where T1.EmpId = 232;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2C Projects') where T1.EmpId = 321;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2C Projects') where T1.EmpId = 475;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2B Projects') where T1.EmpId = 543;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2C Projects') where T1.EmpId = 593;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2C Projects') where T1.EmpId = 595;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2B Projects') where T1.EmpId = 603;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2B Projects') where T1.EmpId = 604;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2B Projects') where T1.EmpId = 656;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2B Projects') where T1.EmpId = 657;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2B Projects') where T1.EmpId = 708;
UPDATE mas_employee T1 SET T1.SectionId = (select A.Id from mas_section A where A.Name = 'B2C Projects') where T1.EmpId = 549;

UPDATE mas_employee T1 SET T1.SectionId = 4 where T1.EmpId = 490;
UPDATE mas_employee T1 SET T1.SectionId = 4 where T1.EmpId = 577;
UPDATE mas_employee T1 SET T1.SectionId = 4 where T1.EmpId = 600;
UPDATE mas_employee T1 SET T1.SectionId = 4 where T1.EmpId = 632;
UPDATE mas_employee T1 SET T1.SectionId = 4 where T1.EmpId = 633;
UPDATE mas_employee T1 SET T1.SectionId = 4 where T1.EmpId = 712;
UPDATE mas_employee T1 SET T1.SectionId = 4 where T1.EmpId = 713;

UPDATE mas_employee T1 SET T1.SectionId = 11 where T1.EmpId = 548;

UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 63;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 108;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 115;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 209;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 337;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 338;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 428;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 587;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 646;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 678;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 718;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Payment') where T1.EmpId = 637;
UPDATE mas_employee T1 SET T1.SectionId = (SELECT A.Id from mas_section A where A.Name = 'Revenue & Follow up') where T1.EmpId = 675;
