UPDATE employeeraw SET Designation = "General Manager, CN & ISP" where EmpId = 4;
UPDATE employeeraw SET Designation = "Manager, B2B" where EmpId = 22;
UPDATE employeeraw SET Designation = "Executive Manager,HRA" where EmpId = 24;
UPDATE employeeraw SET Designation = "Manager, International Services" where EmpId = 26;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 29;
UPDATE employeeraw SET Designation = "Manager, ERP, CC and IT Support" where EmpId = 32;
UPDATE employeeraw SET Designation = "Manager, Payment" where EmpId = 34;
UPDATE employeeraw SET Designation = "Manager, Procurement&Inventory" where EmpId = 35;
UPDATE employeeraw SET Designation = "Manager, SPPD" where EmpId = 37;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 38;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 41;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 42;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 43;
UPDATE employeeraw SET Designation = "Manager, ISP Access" where EmpId = 47;
UPDATE employeeraw SET Designation = "Technical Officer(Core Network)" where EmpId = 56;
UPDATE employeeraw SET Designation = "Technical Officer, IN" where EmpId = 57;
UPDATE employeeraw SET Designation = "Technical Officer, Access Network" where EmpId = 61;
UPDATE employeeraw SET Designation = "Technical Supervisor, Civil" where EmpId = 62;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 63;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 68;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 69;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 71;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 72;
UPDATE employeeraw SET Designation = "Senior Customer Care Executive" where EmpId = 75;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 77;
UPDATE employeeraw SET Designation = "Technical Supervisor, Civil" where EmpId = 82;
UPDATE employeeraw SET Designation = "Technical Supervisor, Access Network" where EmpId = 86;
UPDATE employeeraw SET Designation = "Technical Supervisor, Core Network" where EmpId = 91;
UPDATE employeeraw SET Designation = "Technical Superviser" where EmpId = 97;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 98;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 100;
UPDATE employeeraw SET Designation = "Technician (Core Network)" where EmpId = 102;
UPDATE employeeraw SET Designation = "Technical Supervisor, Civil" where EmpId = 105;
UPDATE employeeraw SET Designation = "Technical Supervisor, Projects" where EmpId = 106;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 108;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 109;
UPDATE employeeraw SET Designation = "Senior Customer Care Executive" where EmpId = 110;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 113;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 115;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 157;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 165;
UPDATE employeeraw SET Designation = "Technical Superviser" where EmpId = 171;
UPDATE employeeraw SET Designation = "Technical Supervisor, Projects" where EmpId = 173;
UPDATE employeeraw SET Designation = "Technical Superviser" where EmpId = 174;
UPDATE employeeraw SET Designation = "Technical  Superviser" where EmpId = 175;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 179;
UPDATE employeeraw SET Designation = "Accountant, Payment" where EmpId = 190;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 193;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 197;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 202;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 203;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 205;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 207;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 209;
UPDATE employeeraw SET Designation = "Technical Superviser" where EmpId = 213;
UPDATE employeeraw SET Designation = "Technical Superviser" where EmpId = 214;
UPDATE employeeraw SET Designation = "Technical Superviser" where EmpId = 216;
UPDATE employeeraw SET Designation = "Store Assistant" where EmpId = 218;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 228;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 229;
UPDATE employeeraw SET Designation = "Technical Supervisor, Projects" where EmpId = 232;
UPDATE employeeraw SET Designation = "Technician, Access Network" where EmpId = 233;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 236;
UPDATE employeeraw SET Designation = "Senior Driver" where EmpId = 237;
UPDATE employeeraw SET Designation = "Manager, Core Network" where EmpId = 245;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 256;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 258;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 259;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 261;
UPDATE employeeraw SET Designation = "Technical Supervisor, Access Network" where EmpId = 264;
UPDATE employeeraw SET Designation = "Technical Supervisor, Access Network" where EmpId = 265;
UPDATE employeeraw SET Designation = "Technical  Superviser" where EmpId = 266;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 267;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 269;
UPDATE employeeraw SET Designation = "Marketing Officer" where EmpId = 272;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 279;
UPDATE employeeraw SET Designation = "Officiating General Manager,Commercial" where EmpId = 280;
UPDATE employeeraw SET Designation = "Technical Officer, Power & Utilities" where EmpId = 284;
UPDATE employeeraw SET Designation = "Accounts Officer" where EmpId = 288;
UPDATE employeeraw SET Designation = "Technical Supervisor, Access Network" where EmpId = 290;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 291;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 292;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 294;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 295;
UPDATE employeeraw SET Designation = "Technician, Civil" where EmpId = 299;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 300;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 310;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 311;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 312;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 313;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 314;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 315;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 316;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 317;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 319;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 321;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 324;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 325;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 326;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 327;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 333;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 337;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 338;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 340;
UPDATE employeeraw SET Designation = "Manager, Administration" where EmpId = 343;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 347;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 348;
UPDATE employeeraw SET Designation = "Manager, B2C" where EmpId = 351;
UPDATE employeeraw SET Designation = "Manager, Civil" where EmpId = 352;
UPDATE employeeraw SET Designation = "Technician, Civil" where EmpId = 353;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 357;
UPDATE employeeraw SET Designation = "Senior Personal Assistant" where EmpId = 360;
UPDATE employeeraw SET Designation = "Manager, Power & Utility" where EmpId = 361;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 364;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 366;
UPDATE employeeraw SET Designation = "Accountant, Payment" where EmpId = 376;
UPDATE employeeraw SET Designation = "Technical Officer, CBS" where EmpId = 380;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 383;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 386;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 387;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 390;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 391;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 410;
UPDATE employeeraw SET Designation = "Technical Officer, B2C" where EmpId = 416;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 419;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 420;
UPDATE employeeraw SET Designation = "Inventory Officer" where EmpId = 421;
UPDATE employeeraw SET Designation = "Accountant, Payment" where EmpId = 427;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 428;
UPDATE employeeraw SET Designation = "Store Assistant" where EmpId = 439;
UPDATE employeeraw SET Designation = "Roaming Coordinator" where EmpId = 441;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 443;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 444;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 445;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 446;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 448;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 450;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 454;
UPDATE employeeraw SET Designation = "General Manager, Finance" where EmpId = 455;
UPDATE employeeraw SET Designation = "Strategy Officer" where EmpId = 460;
UPDATE employeeraw SET Designation = "Optimization  Engineer" where EmpId = 461;
UPDATE employeeraw SET Designation = "Officiating Manager, Human Resource" where EmpId = 462;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 464;
UPDATE employeeraw SET Designation = "Technician (Access network)" where EmpId = 466;
UPDATE employeeraw SET Designation = "Technician, Power" where EmpId = 467;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 469;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 470;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 472;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 475;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 476;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 477;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 478;
UPDATE employeeraw SET Designation = "Core Network Engineer" where EmpId = 479;
UPDATE employeeraw SET Designation = "Technical Oficer (VAS)" where EmpId = 481;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 484;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 485;
UPDATE employeeraw SET Designation = "Technician, Power" where EmpId = 486;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 488;
UPDATE employeeraw SET Designation = "Regional Manager" where EmpId = 490;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 491;
UPDATE employeeraw SET Designation = "Bill Collector" where EmpId = 492;
UPDATE employeeraw SET Designation = "Technical Officer, Access Network" where EmpId = 493;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 498;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 499;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 500;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 501;
UPDATE employeeraw SET Designation = "CBS Engineer" where EmpId = 503;
UPDATE employeeraw SET Designation = "Manager, VAS" where EmpId = 504;
UPDATE employeeraw SET Designation = "CBS Engineer" where EmpId = 505;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 507;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 508;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 509;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 511;
UPDATE employeeraw SET Designation = "Marketing Officer" where EmpId = 513;
UPDATE employeeraw SET Designation = "Technical Officer, Power & Utilities" where EmpId = 515;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 518;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 519;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 520;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 521;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 522;
UPDATE employeeraw SET Designation = "Technician (MIS)" where EmpId = 523;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 524;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 528;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 530;
UPDATE employeeraw SET Designation = "Accounts Officer, Payment" where EmpId = 536;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 537;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 538;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 539;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 540;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 541;
UPDATE employeeraw SET Designation = "Core Network Engineer" where EmpId = 542;
UPDATE employeeraw SET Designation = "Project  Engineer" where EmpId = 543;
UPDATE employeeraw SET Designation = "CBS Engineer" where EmpId = 544;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 546;
UPDATE employeeraw SET Designation = "Manager, Access Network" where EmpId = 547;
UPDATE employeeraw SET Designation = "Optimization Engineer" where EmpId = 548;
UPDATE employeeraw SET Designation = "Project Engineer" where EmpId = 549;
UPDATE employeeraw SET Designation = "Technical Officer,B2B" where EmpId = 550;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 554;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 555;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 556;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 557;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 558;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 559;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 560;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 561;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 563;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 564;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 569;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 570;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 571;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 572;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 573;
UPDATE employeeraw SET Designation = "Technician, Samsung" where EmpId = 577;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 579;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 580;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 582;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 585;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 586;
UPDATE employeeraw SET Designation = "Revenue Officer" where EmpId = 587;
UPDATE employeeraw SET Designation = "Technical Officer, ISP Access" where EmpId = 591;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 593;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 595;
UPDATE employeeraw SET Designation = "Technician, Samsung" where EmpId = 600;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 603;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 604;
UPDATE employeeraw SET Designation = "Contact Center Engineer" where EmpId = 608;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 610;
UPDATE employeeraw SET Designation = "Webmaster" where EmpId = 611;
UPDATE employeeraw SET Designation = "System  Engineer" where EmpId = 613;
UPDATE employeeraw SET Designation = "Human Resource  Officer" where EmpId = 615;
UPDATE employeeraw SET Designation = "Marketing Officer" where EmpId = 616;
UPDATE employeeraw SET Designation = "Marketing Officer" where EmpId = 617;
UPDATE employeeraw SET Designation = "Procurement  Officer" where EmpId = 621;
UPDATE employeeraw SET Designation = "General Manager, SPPD" where EmpId = 622;
UPDATE employeeraw SET Designation = "General Manager, Access" where EmpId = 623;
UPDATE employeeraw SET Designation = "General Manager, MIS" where EmpId = 624;
UPDATE employeeraw SET Designation = "Graphic Designer" where EmpId = 628;
UPDATE employeeraw SET Designation = "PR and Administrative Officer" where EmpId = 629;
UPDATE employeeraw SET Designation = "Technical Officer, Samsung" where EmpId = 630;
UPDATE employeeraw SET Designation = "Technical Officer, Samsung" where EmpId = 631;
UPDATE employeeraw SET Designation = "Technician, Samsung" where EmpId = 632;
UPDATE employeeraw SET Designation = "Technician, Samsung" where EmpId = 633;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 636;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 637;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 642;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 644;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 645;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 646;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 647;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 648;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 651;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 652;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 653;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 654;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 655;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 656;
UPDATE employeeraw SET Designation = "Technician, Projects" where EmpId = 657;
UPDATE employeeraw SET Designation = "CBS Engineer" where EmpId = 663;
UPDATE employeeraw SET Designation = "Engineer VAS" where EmpId = 664;
UPDATE employeeraw SET Designation = "Audit Officer" where EmpId = 665;
UPDATE employeeraw SET Designation = "Technical Officer, ISP Access" where EmpId = 666;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 667;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 668;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 670;
UPDATE employeeraw SET Designation = "Assistant Revenue Officer" where EmpId = 672;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 674;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 675;
UPDATE employeeraw SET Designation = "Human  Resource Officer" where EmpId = 676;
UPDATE employeeraw SET Designation = "Administrative Officer" where EmpId = 677;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 678;
UPDATE employeeraw SET Designation = "Marketing Officer" where EmpId = 679;
UPDATE employeeraw SET Designation = "Access Network Engineer" where EmpId = 680;
UPDATE employeeraw SET Designation = "Technical Officer, Access Network" where EmpId = 681;
UPDATE employeeraw SET Designation = "Technician, Access Network" where EmpId = 682;
UPDATE employeeraw SET Designation = "Technician, Access Network" where EmpId = 683;
UPDATE employeeraw SET Designation = "Technician, Access Network" where EmpId = 684;
UPDATE employeeraw SET Designation = "Technician, Access Network" where EmpId = 685;
UPDATE employeeraw SET Designation = "Technician, Access Network" where EmpId = 686;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 687;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 690;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 691;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 692;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 693;
UPDATE employeeraw SET Designation = "Regional  Manager" where EmpId = 696;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 697;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 700;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 701;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 702;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 703;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 704;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 705;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 706;
UPDATE employeeraw SET Designation = "Project  Engineer" where EmpId = 708;
UPDATE employeeraw SET Designation = "ERP Engineer" where EmpId = 709;
UPDATE employeeraw SET Designation = "Technician, Access Network" where EmpId = 710;
UPDATE employeeraw SET Designation = "General Manager, Commercial" where EmpId = 711;
UPDATE employeeraw SET Designation = "Technician, Samsung" where EmpId = 712;
UPDATE employeeraw SET Designation = "Technician, Samsung" where EmpId = 713;
UPDATE employeeraw SET Designation = "Application Developer" where EmpId = 714;
UPDATE employeeraw SET Designation = "PR and Administrative Officer" where EmpId = 716;
UPDATE employeeraw SET Designation = "Human  Resource Officer" where EmpId = 717;
UPDATE employeeraw SET Designation = "Accountant" where EmpId = 718;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 719;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 720;
UPDATE employeeraw SET Designation = "Marketing Officer" where EmpId = 723;
UPDATE employeeraw SET Designation = "Technician (Core Network)" where EmpId = 724;
UPDATE employeeraw SET Designation = "Technical Officer(Access Network)" where EmpId = 725;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 728;
UPDATE employeeraw SET Designation = "Driver" where EmpId = 733;
UPDATE employeeraw SET Designation = "Human Resource Officer" where EmpId = 735;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 736;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 737;
UPDATE employeeraw SET Designation = "Contact Center Executive" where EmpId = 738;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 739;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 740;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 741;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 742;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 743;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 744;
UPDATE employeeraw SET Designation = "Customer Care Executive" where EmpId = 745;
UPDATE employeeraw SET Designation = "Technical Officer, Power & Utility" where EmpId = 746;
UPDATE employeeraw SET Designation = "Technical Officer, Access Network" where EmpId = 747;
UPDATE employeeraw SET Designation = "Technical Officer, Access Network" where EmpId = 748;
UPDATE employeeraw SET Designation = "Technical Officer, Access Network" where EmpId = 749;
UPDATE employeeraw SET Designation = "Revenue Officer" where EmpId = 750;
UPDATE employeeraw SET Designation = "Inventory Officer" where EmpId = 751;
UPDATE employeeraw SET Designation = "Audit Officer" where EmpId = 752;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 753;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 754;
UPDATE employeeraw SET Designation = "Technician, ISP Access" where EmpId = 755;
UPDATE employeeraw SET Designation = "MFS Engineer" where EmpId = 758;
UPDATE employeeraw SET Designation = "TDA Engineer" where EmpId = 759;
UPDATE employeeraw SET Designation = "Accountant, Payment" where EmpId = 761;
UPDATE employeeraw SET Designation = "Accountant, Payment" where EmpId = 762;
UPDATE employeeraw SET Designation = "Technician, Core Network" where EmpId = 763;