UPDATE mas_employee set Email = 'gm.cncs@tashicell.com' where MobileNo = 77107710;
UPDATE mas_employee set Email = 'manager.ispcore@tashicell.com' where MobileNo = 77103879;
UPDATE mas_employee set Email = 'manager.irs@tashicell.com' where MobileNo = 77101055;
UPDATE mas_employee set Email = 'manager.cns@tashicell.com' where MobileNo = 77104777;
UPDATE mas_employee set Email = 'network1.ispcore@tashicell.com' where MobileNo = 77141717;
UPDATE mas_employee set Email = 'systems1.ispcore@tashicell.com' where MobileNo = 77101066;
UPDATE mas_employee set Email = 'systems2.ispcore@tashicell.com' where MobileNo = 77117550;
UPDATE mas_employee set Email = 'optimization2.cns@tashicell.com' where MobileNo = 77106788;
UPDATE mas_employee set Email = 'optimization3.cns@tashicell.com' where MobileNo = 77103480;
UPDATE mas_employee set Email = 'optimization1.cns@tashicell.com' where MobileNo = 77100055;
UPDATE mas_employee set Email = 'pscore1.cns@tashicell.com' where MobileNo = 77125111;
UPDATE mas_employee set Email = 'cscore1.cns@tashicell.com' where MobileNo = 77102233;
UPDATE mas_employee set Email = 'coordinator.irs@tashicell.com' where MobileNo = 77107831;
UPDATE mas_employee set Email = 'optimization4.cns@tashicell.com' where MobileNo = 77100033;
UPDATE mas_employee set Email = 'gm.mis@tashicell.com' where MobileNo = 77101671;
UPDATE mas_employee set Email = 'manager.cbs@tashicell.com' where MobileNo = 77107009;
UPDATE mas_employee set Email = 'manager.erp@tashicell.com' where MobileNo = 77100001;
UPDATE mas_employee set Email = 'manager.vas@tashicell.com' where MobileNo = 77100222;
UPDATE mas_employee set Email = 'app.cbs@tashicell.com' where MobileNo = 77106699;
UPDATE mas_employee set Email = 'web.cbs@tashicell.com' where MobileNo = 77116699;
UPDATE mas_employee set Email = 'postpaid.cbs@tashicell.com' where MobileNo = 77101122;
UPDATE mas_employee set Email = 'prm.cbs@tashicell.com' where MobileNo = 77141414;
UPDATE mas_employee set Email = 'pcrf.cbs@tashicell.com' where MobileNo = 77495599;
UPDATE mas_employee set Email = 'crm.cbs@tashicell.com' where MobileNo = 77788877;
UPDATE mas_employee set Email = 'prepaid.cbs@tashicell.com' where MobileNo = 77102030;
UPDATE mas_employee set Email = 'cc.mis@tashicell.com' where MobileNo = 77109696;
UPDATE mas_employee set Email = 'erp.mis@tashicell.com' where MobileNo = 77869696;
UPDATE mas_employee set Email = 'itsupport.mis@tashicell.com' where MobileNo = 77465500;
UPDATE mas_employee set Email = 'vas2.mis@tashicell.com' where MobileNo = 77499900;
UPDATE mas_employee set Email = 'vas1.mis@tashicell.com' where MobileNo = 77107665;
UPDATE mas_employee set Email = 'mfs.vas@tashicell.com' where MobileNo = 77875200;
UPDATE mas_employee set Email = 'tda.cbs@tashicell.com' where MobileNo = 77875188;
UPDATE mas_employee set Email = 'gm.finance@tashicell.com' where MobileNo = 77107750;
UPDATE mas_employee set Email = 'manager.procurement@tashicell.com' where MobileNo = 77100123;
UPDATE mas_employee set Email = 'manager.payments@tashicell.com' where MobileNo = 77102525;
UPDATE mas_employee set Email = 'revenue1.finance@tashicell.com' where MobileNo = 77873632;
UPDATE mas_employee set Email = 'revenue2.finance@tashicell.com' where MobileNo = 77451200;
UPDATE mas_employee set Email = 'audit1.finance@tashicell.com' where MobileNo = 77107100;
UPDATE mas_employee set Email = 'audit2.finance@tashicell.com' where MobileNo = 77162929;
UPDATE mas_employee set Email = 'procurement.finance@tashicell.com' where MobileNo = 77811551;
UPDATE mas_employee set Email = 'inventory.finance@tashicell.com' where MobileNo = 77452574;
UPDATE mas_employee set Email = 'accounts.payment@tashicell.com' where MobileNo = 77171752;
UPDATE mas_employee set Email = 'accounts.asset@tashicell.com' where MobileNo = 77141413;
UPDATE mas_employee set Email = 'accountant1.thimphu@tashicell.com' where MobileNo = 77228215;
UPDATE mas_employee set Email = 'accountant2.thimphu@tashicell.com' where MobileNo = 77794777;
UPDATE mas_employee set Email = 'accountant.tsirang@tashicell.com' where MobileNo = 77104949;
UPDATE mas_employee set Email = 'accountant.paro@tashicell.com' where MobileNo = 77105544;
UPDATE mas_employee set Email = 'accountant.gelephu@tashicell.com' where MobileNo = 77629976;
UPDATE mas_employee set Email = 'accountant.wangdue@tashicell.com' where MobileNo = 77109060;
UPDATE mas_employee set Email = 'accountant.mongar@tashicell.com' where MobileNo = 77874048;
UPDATE mas_employee set Email = 'accountant.bumthang@tashicell.com' where MobileNo = 77313096;
UPDATE mas_employee set Email = 'accountant.sjk@tashicell.com' where MobileNo = 77104848;
UPDATE mas_employee set Email = 'accountant.pling@tashicell.com' where MobileNo = 77704767;
UPDATE mas_employee set Email = 'accountant.samtse@tashicell.com' where MobileNo = 77700096;
UPDATE mas_employee set Email = 'accountant.trashigang@tashicell.com' where MobileNo = 77447831;
UPDATE mas_employee set Email = 'accountant1.payment@tashicell.com' where MobileNo = 77101023;
UPDATE mas_employee set Email = 'accountant2.payment@tashicell.com' where MobileNo = 77618179;
UPDATE mas_employee set Email = 'accountant3.payment@tashicell.com' where MobileNo = 77726496;
UPDATE mas_employee set Email = 'accountant.revenue@tashicell.com' where MobileNo = 77876193;
UPDATE mas_employee set Email = 'store.thimphu@tashicell.com' where MobileNo = 77315121;
UPDATE mas_employee set Email = 'md@tashicell.com' where MobileNo = 77109099;
UPDATE mas_employee set Email = 'em.hra@tashicell.com' where MobileNo = 77107711;
UPDATE mas_employee set Email = 'hrd.hrad@tashicell.com' where MobileNo = 77727636;
UPDATE mas_employee set Email = 'hrm.hrad@tashicell.com' where MobileNo = 77475767;
UPDATE mas_employee set Email = 'hr.hrad@tashicell.com' where MobileNo = 77874833;
UPDATE mas_employee set Email = 'adm.hrad@tashicell.com' where MobileNo = 77755245;
UPDATE mas_employee set Email = 'pradm.hrad@tashicell.com' where MobileNo = 77624383;
UPDATE mas_employee set Email = 'pa.hrad@tashicell.com' where MobileNo = 77471147;
UPDATE mas_employee set Email = 'gm.access@tashicell.com' where MobileNo = 77101117;
UPDATE mas_employee set Email = 'manager.power@tashicell.com' where MobileNo = 77108999;
UPDATE mas_employee set Email = 'manager.ispaccess@tashicell.com' where MobileNo = 77113097;
UPDATE mas_employee set Email = 'manager.access@tashicell.com' where MobileNo = 77157715;
UPDATE mas_employee set Email = 'gm.commercial@tashicell.com' where MobileNo = 77113248;
UPDATE mas_employee set Email = 'rm.paro@tashicell.com' where MobileNo = 77101666;
UPDATE mas_employee set Email = 'rm.gelephu@tashicell.com' where MobileNo = 77100280;
UPDATE mas_employee set Email = 'rm.trashigang@tashicell.com' where MobileNo = 77113953;
UPDATE mas_employee set Email = 'rm.bumthang@tashicell.com' where MobileNo = 77352911;
UPDATE mas_employee set Email = 'rm.sjk@tashicell.com' where MobileNo = 77109494;
UPDATE mas_employee set Email = 'rm.thimphu@tashicell.com' where MobileNo = 77173030;
UPDATE mas_employee set Email = 'rm.pling@tashicell.com' where MobileNo = 77763682;
UPDATE mas_employee set Email = 'rm.wangdue@tashicell.com' where MobileNo = 77101918;
UPDATE mas_employee set Email = 'rm.mongar@tashicell.com' where MobileNo = 77900700;
UPDATE mas_employee set Email = 'phub.gyeltshen@tashicell.com' where MobileNo = 77108822;
UPDATE mas_employee set Email = 'mo.samsung@tashicell.com' where MobileNo = 77118413;
UPDATE mas_employee set Email = 'mo.strategy@tashicell.com' where MobileNo = 77443366;
UPDATE mas_employee set Email = 'mo.marketing@tashicell.com' where MobileNo = 77106688;
UPDATE mas_employee set Email = 'mo.sales@tashicell.com' where MobileNo = 77117267;
UPDATE mas_employee set Email = 'gm.sppd@tashicell.com' where MobileNo = 77113026;
UPDATE mas_employee set Email = 'manager.civil@tashicell.com' where MobileNo = 77107524;
UPDATE mas_employee set Email = 'manager.b2bprojects@tashicell.com' where MobileNo = 77147788;
UPDATE mas_employee set Email = 'manager.b2cprojects@tashicell.com' where MobileNo = 77101691;
UPDATE mas_employee set Email = 'strategy.officer@tashicell.com' where MobileNo = 77118907;
UPDATE mas_employee set Email = 'manager.asprojects@tashicell.com' where MobileNo = 77101010;


UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 216);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 292);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 682);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 236);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 454);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 207);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 300);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 703);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 338);
UPDATE mas_hierarchy SET ReportingLevel1EmployeeId = '1999' where EmployeeId = (select Id from mas_employee where EmpId = 697);

UPDATE mas_employee SET BasicPay = 11891 where EmpId = '541';
UPDATE mas_employee SET BasicPay = 13409 where EmpId = '292';
UPDATE mas_employee SET BasicPay = 13409 where EmpId = '294';
UPDATE mas_employee SET BasicPay = 13717 where EmpId = '291';
UPDATE mas_employee SET BasicPay = 13409 where EmpId = '295';
UPDATE mas_employee SET BasicPay = 11891 where EmpId = '538';
UPDATE mas_employee SET BasicPay = 11616 where EmpId = '539';
UPDATE mas_employee SET BasicPay = 10464 where EmpId = '236';
UPDATE mas_employee SET BasicPay = 11891 where EmpId = '540';
UPDATE mas_employee SET BasicPay = 13409 where EmpId = '290';
UPDATE mas_employee SET BasicPay = 14025 where EmpId = '233';
UPDATE mas_employee SET BasicPay = 22459 where EmpId = '490';
UPDATE mas_employee SET BasicPay = 10464 where EmpId = '237';
UPDATE mas_employee SET BasicPay = 25856 where EmpId = '542';
UPDATE mas_employee SET BasicPay = 24070 where EmpId = '288';
UPDATE mas_employee SET BasicPay = 10560 where EmpId = '647';
UPDATE mas_employee SET BasicPay = 25270 where EmpId = '543';
UPDATE mas_employee SET BasicPay = 13101 where EmpId = '299';
UPDATE mas_employee SET BasicPay = 15717 where EmpId = '232';
UPDATE mas_employee SET BasicPay = 21922 where EmpId = '708';


UPDATE mas_employee SET MobileNo = '77390373' where CIDNo = 30303000016;
UPDATE mas_employee SET MobileNo = '77223688' where CIDNo = 10205002992;
UPDATE mas_employee SET MobileNo = '77645335' where CIDNo = 10902000766;
UPDATE mas_employee SET MobileNo = '77352368' where CIDNo = 11508002115;
UPDATE mas_employee SET MobileNo = '77107171' where CIDNo = 11915001349;